### ISSUE TITLE
Support for named routes and middleware? 

### ISSUE THREAD

**Issue by ActuallyACat** [appzcoder/lumen-route-list#1]
It would be pretty handy to include named routes and middleware in route:list.

**Comment by sohelamin** [comment]
Hi @ActuallyACat thanks for looking the package and sharing your idea.

I've received a pull request. I will merge it after checking.

**Comment by ActuallyACat** [comment]
Cheers @sohelamin. Will take a look when the PR is merged :+1:

**Comment by sohelamin** [comment]
Hi @ActuallyACat 

I've just merged the PR and also released a stable version.
You can check now.
