### ISSUE TITLE
Class router does not exist

### ISSUE THREAD

**Issue by ant-ia** [appzcoder/lumen-route-list#6]
Hi, with lumen 5.4.7 obtain this error after php artisan route:list

  [ReflectionException]
  Class router does not exist

can u help me?
thanks.

**Comment by sohelamin** [comment]
Can you have a try with the new update?

**Comment by ant-ia** [comment]
@sohelamin yes, with the new update! but not work!

**Comment by ant-ia** [comment]
@sohelamin but i have the same error

**Comment by sohelamin** [comment]
@ant-ia I just checked on Lumen 5.4.7 and everything working fine.
Can you check it again on fresh installation?
